execution_env=local
appURL=https://tutorialsninja.com/demo/
email=userayu@example.com
password=Password@123
searchProductName=iMac
newPassword=ayu@0806

email2=userayuag12@example.com
email2Password=Pass@456
